GW_subjects = [
	["Fist", 2],
	["Box", 1],
	["Master", 2],
	["Soldier", 2],
	["Reflex", 2],
	["Inferno", 2],
	["War", 2],
	["Vendetta", 2],
	["Maximum", 0],
	["Sudden", 0],
	["Instant", 0],
	["Battle", 2],
	["Infinite", 0],
	["Duke", 2],
	["Lord", 2],
	["Peasant", 2],
	["Double", 0],
	["Fatal", 0],
	["Quadruple", 0 ],
	["Extreme", 0],
	["Commander", 2],
	["Slave", 2],
	["Total", 0],
	["Dominator",2],
	["Demolisher",2],
	["Destroyer",2],
	["Executioner", 2],
	["Speedy", 0],
	["Captain", 2],
	["Colonel", 2],
	["General", 2],
	["Sergeant", 2],
	["Commodore", 2],
	["Major", 2],
	["Marshal", 2],
	["Absolute", 0],
	["Complete", 0],
	["Sheer", 0],
	["Unlimited", 0],
	["Utter", 0],
	["Simple", 0],
	["Unconditional", 0],
	["Eternal", 0],
	["Perpetual", 0],
	["Immense", 0],
	["Everlasting", 0],
	["Enormous", 0],
	["Colossal", 0],
	["Colossus", 2],
	["Excessive", 0],
	["Gigantic", 0],
	["Monstrous", 0],
	["Dealer", 2],
	["Hell's", 0],
	["Dynamic", 0],
	["Inconspicious", 0],
	["Prudent", 0],
	["Inglorious", 0],
	["Little", 0],
	["Miniscule", 0],
	["Tiny", 0],
	["Monster", 0],
	["Cynical", 1],
	["Likely", 0],
	["Unlikely", 0],
	["Possible", 0],
	["Desperate", 0],
	["Ethereal", 0],
	["Fearless", 0],
	["Fierce", 0],
	["Frantic", 0],
	["Fantastic", 0],
	["Feeble", 0],
	["Guttural", 0],
	["Grotesque", 0],
	["Ghostly", 0],
	["Extra", 0],
	["Minor", 0],
	["Unsuspecting", 0],
	["Intimidating", 0],
	["Unrivalled", 0],
	["Constant", 0],
	["Fresh",0],
	["Pedantic",0],
	["Sneaky",0],
	["Terrible",0],
	["Perilous",0],
	["Practical", 0],
	["Dependable", 0],
	["Reliable", 0],
	["Ironic", 0],
	["Exceptional", 0]

];

GW_descriptors = [
	" ",
	" of ",
	" for "	
];

GW_additions = [
	" and ",
	" by ",
	" with "
];

GW_attributes = [
	"Deliverance",	
	"Setback",	
	"Destruction",	
	"Wreck",
	"Fanatic",
	"Overkill",
	"Vengeance",
	"Retribution",
	"Danger",
	"Conquest",
	"Termination",
	"Domination",
	"Risk",
	"Punishment",
	"Blood",
	"Execution",
	"Prejudice",
	"Extermination",
	"Justice",
	"Revenge",
	"Death",
	"Jeopardy",
	"Humiliation",
	"Surrender",
	"Intimidation",
	"Victory",
	"Assassination",
	"Action",
	"Honor",
	"Retreat",
	"Payback",
	"Impact",
	"Risk",
	"Domination",
	"Demolition",
	"Speed",
	"Doom",
	"Demise",
	"Fury",
	"Bastard",
	"Examination",
	"Preservation",
	"Concern",
	"Escape",
	"Getaway",
	"Punch",
	"Decapitation",
	"Soothing",
	"Wobble",
	"Suspect",
	"Shock",
	"Delivery",
	"Arrival",
	"Calling",
	"Disposal",
	"Detonation",
	"Grin",
	"Gaze",
	"Manwagon",
	"Scuttler",
	"Wheels",
	"Success",
	"Failure",
	"Accident",
	"Inspection",
	"Contradiction",
	"Irony",
	"Chaos",
	"Calamity",
	"Hilarity",
	"Pursuit",
	"Proposal",
	"Test",
	"Experiment"
];